services:
  db-goals:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: financialgoalsmanager_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MY_SENHA123!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    restart: unless-stopped
    networks:
      - fg_network
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S db-goals -U sa -P \"MY_SENHA123!\" -Q \"SELECT 1\" >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 20s

  financialgoalsmanager.api:
    build:
      context: .
      dockerfile: FinancialGoalsManager.API/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: financialgoalsmanagerapi
    container_name: financialgoalsmanager_api
    depends_on:
      - db-goals
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db-goals,1433;Database=FinancialGoalsManager;User Id=sa;Password=MY_SENHA123!;TrustServerCertificate=True;
    ports:
      - "5000:80"
    restart: unless-stopped
    networks:
      - fg_network

  adminer:
    image: adminer:latest
    container_name: financialgoalsmanager_adminer
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db-goals
    networks:
      - fg_network


volumes:
  mssql-data:

networks:
  fg_network:
    driver: bridge
